packages:
  - "."

allowBuilds:
  '0': '@nestjs/core'
  '1': '@prisma/client'
  '2': '@prisma/engines'
  '3': bcrypt
  '4': msgpackr-extract
  '5': prisma
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  msgpackr-extract: true
  prisma: true
